version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - 'account-book:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: account-book
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}

volumes:
  account-book:
